jobs:
- job: PublishSymbols
  displayName: "Publish symbols"
  condition: and(succeeded(), ne(variables['Skip.PublishPackage'], 'true'))
  timeoutInMinutes: 120
  pool:
    # Symbols conversion tool only runs on Windows
    name: $(WINDOWSPOOL)
    image: $(WINDOWSVMIMAGE)
    os: windows

  steps:
  - checkout: azure-sdk-build-tools

  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'specific'
      project: '$(System.TeamProjectId)'
      pipeline: '$(Build.DefinitionId)'
      buildVersionToDownload: 'specific'
      runId: '5676627'
      artifactName: 'binaries_signed'
      targetPath: '$(Pipeline.Workspace)/binaries_signed'

  - pwsh: |
      Write-Host 'Contents of $(Pipeline.Workspace)/binaries_signed:'
      Get-ChildItem -Path '$(Pipeline.Workspace)/binaries_signed' -Recurse
    displayName: 'artifact contents'

  # - download: current
  #   displayName: Download binaries_signed
  #   artifact: binaries_signed

  - template: /pipelines/steps/publish-symbols.yml@azure-sdk-build-tools
    parameters:
      BuildToolsRepositoryPath: $(Build.SourcesDirectory)
      PackagesPath: $(Pipeline.Workspace)/binaries_signed
      StagingDirectory: $(Build.ArtifactStagingDirectory)

  - template: /eng/common/pipelines/templates/steps/publish-1es-artifact.yml
    parameters:
      ArtifactPath: $(Build.ArtifactStagingDirectory)
      ArtifactName: symbols_published
